version: "3"

services:
  awesomeapi:
    build: ./awesomeapi
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend

  awesomeapiswagger:
    image: swaggerapi/swagger-ui:v3.0.5
    environment:
      API_URL: 'http://localhost:3000/swagger.json'
    ports:
      - "3001:8080"
    networks:
      - frontend

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASS: 'pass'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  frontend:
  backend:
